django03/django03/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('task_manager.urls')),
    path('profile/', include('user_profile.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
] + (static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))

django03/task_manager/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('tasks/', views.TaskListView.as_view(), name='task_list'),
    path('task/<int:pk>/', views.TaskDetailView.as_view(), name='task_detail'),
    path('task/update/<int:pk>/', views.TaskUpdateView.as_view(), name='task_update'),
    path('task/create/', views.TaskCreateView.as_view(), name='task_create'),
    path('task/delete/<int:pk>/', views.TaskDeleteView.as_view(), name='task_delete'),
]

django03/task_manager/models.py
from datetime import date, datetime
from django.contrib.auth import get_user_model
from django.db import models
from django.utils.translation import gettext_lazy as _
from django.urls import reverse


User = get_user_model()


class Task(models.Model):
    content = models.CharField(_('content'), max_length=250)
    note = models.TextField(_('note'), max_length=10000, null=True, blank=True,)
    start = models.DateField(_('start'),null=True, blank=True,)
    finish = models.DateField(_('finish'),null=True, blank=True,)
    owner = models.ForeignKey(
        User,
        verbose_name=_("owner"),
        on_delete=models.CASCADE,
        related_name='owner_tasks',
        null=True, blank=True,
    )
    assignee = models.ForeignKey(
        User,
        verbose_name=_("assignee"),
        on_delete=models.CASCADE,
        related_name='assignee_tasks',
        null=True, blank=True,
    )
    PRIORITY_CHOICES = (
        (1, _('Low')),
        (2, _('Medium')),
        (3, _('High')),
        (4, _('Critical')),
    )
    priority = models.PositiveSmallIntegerField(
        _("priority"), 
        choices=PRIORITY_CHOICES, 
        default=2,
        db_index=True,
    )
    STATUS_CHOICES = (
        (0, _('Not started')),
        (1, _('In progess')),
        (2, _('On hold')),
        (3, _('Cancelled')),
        (4, _('Completed')),
    )
    status = models.PositiveSmallIntegerField(
        _("status"), 
        choices=STATUS_CHOICES, 
        default=0,
        db_index=True,
    )
    created_at = models.DateTimeField(_("Created"), auto_now_add=True)
    updated_at = models.DateTimeField(_("Updated"), auto_now=True)
    is_read = models.BooleanField(default=False)
    read_at = models.DateTimeField(null=True)    

    @property
    def is_overdue(self):
        if self.finish and date.today() > self.finish and self.status < 2:
            return True
        return False

    class Meta:
        ordering = ['status', 'finish', '-priority']
        verbose_name = _("task")
        verbose_name_plural = _("tasks")

    def mark_task_as_read(task):
        task.is_read = True
        task.read_at = datetime.now()
        task.save()

    def __str__(self):
        return f"{self.content} - {self.get_status_display()}"

    def get_absolute_url(self):
        return reverse("task_detail", kwargs={"pk": self.pk})
    

class TaskComment(models.Model):
    content = models.CharField(_('content'), max_length=250)
    task = models.ForeignKey(
        Task,
        verbose_name=_("task"),
        on_delete=models.CASCADE,
        related_name='comments',
        null=True, blank=True,
    )
    commenter = models.ForeignKey(
        User,
        verbose_name=_("commenter"),
        on_delete=models.CASCADE,
        related_name='task_comments',
        null=True, blank=True,
    )
    created_at = models.DateTimeField(_("Created"), auto_now_add=True)
    
    class Meta:
        ordering = ['-created_at']
        verbose_name = _("task comment")
        verbose_name_plural = _("task comments")

    def __str__(self):
        return self.content

    def get_absolute_url(self):
        return reverse("taskcomment_detail", kwargs={"pk": self.pk})
    

django03/task_manager/forms.py
from django import forms
from . import models


class DateInput(forms.DateInput):
    input_type = 'date'


class TaskForm(forms.ModelForm):
    class Meta:
        model = models.Task
        fields = ('content', 'note', 'start', 'finish', 'owner', 'assignee', 'priority', 'status')
        widgets = {
            'owner' : forms.HiddenInput(),
            'start' : DateInput(),
            'finish' : DateInput(),
        }


class TaskCommentForm(forms.ModelForm):
    class Meta:
        model = models.TaskComment
        fields = ('content', 'task', 'commenter')
        widgets = {
            'task' : forms.HiddenInput(),
            'commenter' : forms.HiddenInput(),
        }

django03/task_manager/views.py
from datetime import date, timedelta
from typing import Any, Dict
from typing import Any
from django import forms
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.http import HttpResponse
from django.db.models import Q
from django.shortcuts import render
from django.views import generic
from django.shortcuts import render, get_object_or_404, reverse
from django.urls import reverse, reverse_lazy
from django.utils.translation import gettext_lazy as _
from . forms import TaskForm
from . models import Task
from . forms import TaskCommentForm
from django.db.models import Count


def index(request):
    num_tasks = Task.objects.all().count()
    num_tasks_not_started = Task.objects.filter(status__exact=0).count
    context = {
        'num_tasks' : num_tasks,
    }
    return render(request, 'task_manager/index.html', context)


class TaskListView(generic.ListView):
    model = Task
    paginate_by = 10
    template_name = "task_manager/task_list.html"

    def get_queryset(self):
        user = self.request.user
        return Task.objects.filter(Q(owner__username=user.username) | Q(assignee__username=user.username))
    
    # For calculation of tasks with different statuses for logged in user 
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = self.request.user
        task_counts = (
            Task.objects.filter(assignee=user)
            .values('status')
            .annotate(count=Count('status'))
        )
        # Convert status values to words
        for count in task_counts:
            count['status_display'] = Task.STATUS_CHOICES[count['status']][1]
        context['task_counts'] = task_counts
        return context


class TaskDetailView(generic.edit.FormMixin, generic.DetailView):
    model = Task
    template_name = "task_manager/task_detail.html"
    form_class = TaskCommentForm

    def get_initial(self) -> Dict[str, Any]:
        initial = super().get_initial()
        initial['task'] = self.get_object()
        initial['commenter'] = self.request.user
        return initial

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form: Any) -> HttpResponse:
        form.instance.task = self.get_object()
        form.instance.commenter = self.request.user
        form.save()
        messages.success(self.request, _('Comment posted successfully!'))
        return super().form_valid(form)

    def get_success_url(self) -> str:
        return reverse('task_detail', kwargs={'pk':self.get_object().pk})


class TaskCreateView(LoginRequiredMixin, UserPassesTestMixin, generic.CreateView):
    model = Task
    form_class = TaskForm
    template_name = 'task_manager/task_form.html'
    success_url = reverse_lazy('task_list')

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)
        return context
    
    def get_initial(self) -> Dict[str, Any]:
        # self.task = get_object_or_404(Task, id=self.request.GET.get('task_id'))
        initial = super().get_initial()
        initial['start'] = date.today()
        initial['finish'] = date.today() + timedelta(days=7)
        initial['status'] = 0
        initial['priority'] = 2
        initial['owner'] = self.request.user
        if not self.request.user.is_staff and not self.request.user.is_superuser:
            initial['assignee'] = self.request.user
        return initial

    def form_valid(self, form):
        form.instance.owner = self.request.user
        messages.success(self.request, _('Task created successfully!'))
        return super().form_valid(form)
    
    def get_form(self, form_class=None):
        form = super().get_form(form_class)
        
        if not self.request.user.is_staff and not self.request.user.is_superuser:
            form.fields['assignee'].initial = self.request.user.username
            form.fields['assignee'].widget = forms.HiddenInput()

        return form

    # Checks that the user passes the given test
    def test_func(self):
        return self.request.user.is_authenticated
                  

class TaskUpdateView(LoginRequiredMixin, UserPassesTestMixin, generic.UpdateView):
    model = Task
    form_class = TaskForm
    template_name = 'task_manager/task_form.html'
    success_url = reverse_lazy('task_list')

    def get_form(self, form_class=None):
        form = super().get_form(form_class)
        if self.object.owner == self.request.user and not self.request.user.is_superuser:
            form.fields['assignee'].widget = forms.HiddenInput()
        elif self.object.owner != self.request.user and not self.request.user.is_superuser:
            # If user is superuser, exclude all fields except "status"
            for field_name in form.fields:
                if field_name != 'status':
                    form.fields[field_name].widget = forms.HiddenInput()
        return form
    
    def form_valid(self, form):
        messages.success(self.request, _('Task updated successfully!'))
        return super().form_valid(form)

    # Checks that the user passes the given test
    def test_func(self):
        obj = self.get_object()
        if obj.owner == self.request.user or obj.assignee == self.request.user:
            return True
        else:
            return False


class TaskDeleteView(
    LoginRequiredMixin,
    UserPassesTestMixin,
    generic.DeleteView
):
    model = Task
    template_name = 'task_manager/task_delete.html'
    success_url = reverse_lazy('task_list')

    def form_valid(self, form):
        messages.success(self.request, _('Task deleted successfully!'))
        return super().form_valid(form)

    def test_func(self) -> bool | None:
        obj = self.get_object()
        return obj.owner == self.request.user
    

django03/task_manager/templates/task_manager/index.html
{% extends 'base.html' %}
{% block title %}Welcome to {{ block.super }}{% endblock title %}
{% block content %}
    <div class="row">
        <h1>Task manager</h1>
    </div>
    <div class="row">
        <p>A task manager is a tool that helps individuals or teams organize, track, and prioritize their tasks and activities. It typically provides features like task creation, assignment, due dates, progress tracking, reminders, and collaboration, allowing users to efficiently manage their workload and stay organized. It serves as a central hub for managing and monitoring tasks, improving productivity and facilitating effective task management.</p>
    </div>
    {% if not user.is_authenticated %}
        <div class="row">
            <p>To access Task manager, please <a href="{% url 'login' %}">Login</a>.
        </div>
    {% endif %}
{% endblock content %}

django03/task_manager/templates/task_manager/task_delete.html
{% extends 'base.html' %}
{% block title %}Task delete{% endblock title %}
{% block content %}
    <div class="row">
        <h1>Task delete</h1>
    </div>
    <table class="table table-stripped">
        <tr>
            <td>Task ID:</td>
            <td>{{ task.id }}</td>
        </tr>
            <td>Task:</td>
            <td>{{ task.content }}</td>
        </tr>
        <tr>
            <td>Manager:</td>
            <td>{{ task.owner.first_name }} {{ task.owner.last_name }}</td>
        </tr>
        <tr>
            <td>Manager email:</td>
            <td>{{ task.owner.email }}</td>
        </tr>
        <tr>
            <td>Assignee:</td>
            <td> {{ task.assignee.first_name }} {{ task.assignee.last_name }}</td>
        </tr>
            <td>Assignee email:</td>
            <td>{{ task.assignee.email }}</td>
        </tr>
        <tr>
            <td>Status:</td>
            <td>{{ task.get_status_display }}</td>
        </tr>
        <tr>
            <td>Start:</td>
            <td>{{ task.start }}</td>
        </tr>
        <tr>
            <td>Finish:</td>
            <td>{{ task.finish }}</td>
        </tr>
        <tr>
            <td>Priority:</td>
            <td>{{ task.get_priority_display }}</td>
        <tr>
        </tr>
            <td>Created by:</td>
            <td>{{ task.owner.first_name }} {{ task.owner.last_name }}</td>
        </tr>
        <tr>
            <td>Created at:</td>
            <td>{{ task.created_at }}</td>
        </tr>
    </table>
    <form action="{{ request.path }}" method="post">
        {% csrf_token %}
        <button type="submit">Confirm</button>
        <a href="{% url 'task_list' %}">Cancel</a>
    </form>
{% endblock content %}

django03/task_manager/templates/task_manager/task_detail.html
{% extends 'base.html' %}
{% load static %}
{% block title %} {{ block.super }} {% endblock title %}
{% block content %}
    {% if task.owner.username == user.username or task.assignee.username == user.username %}
        <div class="row">
            <h1>Task details</h1>
        </div>
        <table class="table table-stripped">
            <tr>
                <td>Task ID:</td>
                <td>{{ task.id }}</td>
            </tr>
                <td>Task:</td>
                <td>{{ task.content }}</td>
            </tr>
            </tr>
                <td>Task notes:</td>
                <td>{{ task.note }}</td>
            </tr>
            <tr>
                <td>Manager:</td>
                <td>{{ task.owner.first_name }} {{ task.owner.last_name }}</td>
            </tr>
            <tr>
                <td>Manager email:</td>
                <td>{{ task.owner.email }}</td>
            </tr>
            <tr>
                <td>Assignee:</td>
                <td> {{ task.assignee.first_name }} {{ task.assignee.last_name }}</td>
            </tr>
                <td>Assignee email:</td>
                <td>{{ task.assignee.email }}</td>
            </tr>
            <tr>
                <td>Status:</td>
                <td>{{ task.get_status_display }}</td>
            </tr>
            <tr>
                <td>Start:</td>
                <td>{{ task.start }}</td>
            </tr>
            <tr>
                <td>Finish:</td>
                <td>{{ task.finish }}</td>
            </tr>
            <tr>
                <td>Priority:</td>
                <td>{{ task.get_priority_display }}</td>
            <tr>
            </tr>
                <td>Created by:</td>
                <td>{{ task.owner.first_name }} {{ task.owner.last_name }}</td>
            </tr>
            <tr>
                <td>Created at:</td>
                <td>{{ task.created_at }} (GMT)</td>
            </tr>
            <tr>
                <td>Last updated at:</td>
                <td>{{ task.updated_at }} (GMT)</td>
            </tr>
        </table>
        <div class="row">
            <h2>Comments</h3>
        <div class="row">
        <form method="post" action="{{ request.path }}">
            <div class="row">
                <p>Leave your comment</p>
            </div>
            {% csrf_token %}
            <div class="task-form">
                {{ form.as_p }}
            </div>
            <button type="submit">Post comment</button>
        </form>
        {% if task.comments.count > 0 %}
            <ul>
                {% for comment in task.comments.all %}
                    <li>{{ comment.commented_at }} by {{ comment.commenter }}<br>{{ comment.content }}</li>
                {% endfor %}
            </ul>
        {% endif %}
    {% else %}
        <p>You have no access to view this task</p>
    {% endif %}
{% endblock content %}

django03/task_manager/templates/task_manager/task_form.html
{% extends 'base.html' %}
{% load static %}
{% block title %} {{ block.super }} {% endblock title %}
{% block content %}
    {% if task.id %}
        <h1>Update task</h1>
        <p>Task: {{ task.content }}</p>
    {% else %}
        <h1>New task</h1>
    {% endif %}
    <form method = "post" action="{{ request.path }}?task_id={{ task.id }}">
        {% csrf_token %}
        <div class="task-form">
            {{ form.as_p }}
        </div>
        <button type="submit">Confirm</button>
    </form>
{% endblock content %}

django03/task_manager/templates/task_manager/task_list.html
{% extends 'base.html' %}
{% load static %}
{% block title %} {{ block.super }} {% endblock title %}
{% block content %}
    <div class="row">
        <h1>Task Management</h1>
    </div>
    <div class="row">
        {% for count in task_counts %}
        <div class="col {% if count.status == 0 %}bg-secondary p-2 text-dark bg-opacity-10
            {% elif count.status == 1 %}bg-success p-2 text-dark bg-opacity-25
            {% elif count.status == 2 %}bg-primary p-2 text-dark bg-opacity-25
            {% elif count.status == 3 %}bg-danger p-2 text-dark bg-opacity-25
            {% elif count.status == 4 %}bg-success p-2 text-dark bg-opacity-50
            {% endif %}">Tasks<br>{{ count.status_display }}<br>{{ count.count }}
        </div>
        {% endfor %}
    </div>
    <div class="row">
        <p><a class="" href="{% url 'task_create' %}">Create new</a></p>
    </div>
    {% if task_list %}
        {% include 'includes/paginator_nav.html' %}
        <table class="table table-bordered">
            <tr>
                <th>ID</th>
                <th>Task</th>
                <th>Manager</th>
                <th>Assignee</th>
                <th>Status</th>                
                <th>Start</th>
                <th>Finish</th>
                <th>Is overdue</th>
                <th>Priority</th>
                <th>Actions</th>
            </tr>
            {% for task in task_list %}
                <tr>
                    <td>{{ task.id }}</td>
                    <td>{{ task.content }}</td>
                    <td>{{ task.owner.first_name }} {{ task.owner.last_name }}</td>  
                    <td>{{ task.assignee.first_name }} {{ task.assignee.last_name }}</td>
                    <td class="{% if task.status == 0 %}bg-secondary p-2 text-dark bg-opacity-10
                        {% elif task.status == 1 %}bg-success p-2 text-dark bg-opacity-25
                        {% elif task.status == 2 %}bg-primary p-2 text-dark bg-opacity-25
                        {% elif task.status == 3 %}bg-danger p-2 text-dark bg-opacity-25
                        {% elif task.status == 4 %}bg-success p-2 text-dark bg-opacity-50
                        {% endif %}">{{ task.get_status_display }}</td>
                    <td>{{ task.start }}</td>
                    <td class="{% if task.is_overdue %}bg-danger p-2 text-dark bg-opacity-25{% endif %}">{{ task.finish }}</td>
                    <td>{{ task.is_overdue }}</td>
                    <td class="{% if task.priority == 1 %}bg-primary p-2 text-dark bg-opacity-10
                        {% elif task.priority == 2 %}bg-primary p-2 text-dark bg-opacity-25
                        {% elif task.priority == 3 %}bg-primary p-2 text-dark bg-opacity-50
                        {% elif task.priority == 4 %}bg-primary p-2 text-white bg-opacity-75
                        {% endif %}">{{ task.get_priority_display }}</td>  
                        <td>
                            <a href="{% url 'task_detail' task.pk %}" style="text-decoration: none;">&#128269;</a>
                            <a href="{% url 'task_update' task.pk %}" style="text-decoration: none;">&#128221;</a>
                            {% if task.owner.username == user.username %}
                                <a href="{% url 'task_delete' task.pk %}" style="text-decoration: none;">&#10060;</a>
                            {% endif %}
                        </td>
                </tr>
            {% endfor %}
        </table>
    {% endif %}
{% endblock content %}